import matplotlib.pyplot as plt
import pandas as pd

excel = pd.read_excel("log_indoor.xlsx")

plt.plot(excel["Time"], excel["Indoor Temperature"], color="green", label="Indoor Temperature")
plt.xlabel("Time(s)")
plt.ylabel("Indoor Temperature(°C)")
plt.savefig("inTemp.png")
plt.close()

plt.plot(excel["Time"], excel["Outdoor Temperature"], color="green", label="Outdoor Temperature")
plt.xlabel("Time(s)")
plt.ylabel("Outdoor Temperature(°C)")
plt.savefig("outTemp.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor Humidity"], color="green", label="Indoor Humidity")
plt.xlabel("Time(s)")
plt.ylabel("Indoor Humidity(%RH)")
plt.savefig("inHum.png")
plt.close()

plt.plot(excel["Time"], excel["Outdoor Humidity"], color="green", label="Outdoor Humidity")
plt.xlabel("Time(s)")
plt.ylabel("Outdoor Humidity(%RH)")
plt.savefig("outHum.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor CO2"], color="green", label="Indoor CO2")
plt.xlabel("Time(s)")
plt.ylabel("Indoor CO2(ppm)")
plt.savefig("inCO2.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor Pressure"], color="green", label="Indoor Pressure")
plt.xlabel("Time(s)")
plt.ylabel("Indoor Pressure(hPa)")
plt.savefig("inPres.png")
plt.close()

plt.plot(excel["Time"], excel["Outdoor Pressure"], color="green", label="Outdoor Pressure")
plt.xlabel("Time(s)")
plt.ylabel("Outdoor Pressure(hPa)")
plt.savefig("outPres.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor PM2.5"], color="green", label="Indoor PM2.5")
plt.xlabel("Time(s)")
plt.ylabel("Indoor PM2.5(μg/m³)")
plt.savefig("inPM25.png")
plt.close()

plt.plot(excel["Time"], excel["Outdoor PM2.5"], color="green", label="Outdoor PM2.5")
plt.xlabel("Time(s)")
plt.ylabel("Outdoor PM2.5(μg/m³)")
plt.savefig("outPM25.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor PM10"], color="green", label="Indoor PM10")
plt.xlabel("Time(s)")
plt.ylabel("Indoor PM10(μg/m³)")
plt.savefig("inPM10.png")
plt.close()

plt.plot(excel["Time"], excel["Outdoor PM10"], color="green", label="Outdoor PM10")
plt.xlabel("Time(s)")
plt.ylabel("Outdoor PM10(μg/m³)")
plt.savefig("outPM10.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor TVOC"], color="green", label="Indoor TVOC")
plt.xlabel("Time(s)")
plt.ylabel("Indoor TVOC(mg/m³)")
plt.savefig("inTVOC.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor Temperature"], color="green", label="Indoor Temperature")
plt.plot(excel["Time"], excel["Outdoor Temperature"], color="red", label="Outdoor Temperature")
plt.xlabel("Time(s)")
plt.ylabel("Temperature(°C)")
plt.legend(loc="best")
plt.savefig("temp.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor Humidity"], color="green", label="Indoor Humidity")
plt.plot(excel["Time"], excel["Outdoor Humidity"], color="red", label="Outdoor Humidity")
plt.xlabel("Time(s)")
plt.ylabel("Humidity(%RH)")
plt.legend(loc="best")
plt.savefig("hum.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor Pressure"], color="green", label="Indoor Pressure")
plt.plot(excel["Time"], excel["Outdoor Pressure"], color="red", label="Outdoor Pressure")
plt.xlabel("Time(s)")
plt.ylabel("Pressure(hPa)")
plt.legend(loc="best")
plt.savefig("pres.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor PM2.5"], color="green", label="Indoor PM2.5")
plt.plot(excel["Time"], excel["Outdoor PM2.5"], color="red", label="Outdoor PM2.5")
plt.xlabel("Time(s)")
plt.ylabel("PM2.5(μg/m³)")
plt.legend(loc="best")
plt.savefig("PM25.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor PM10"], color="green", label="Indoor PM10")
plt.plot(excel["Time"], excel["Outdoor PM10"], color="red", label="Outdoor PM10")
plt.xlabel("Time(s)")
plt.ylabel("PM10(μg/m³)")
plt.legend(loc="best")
plt.savefig("PM10.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor TVOC"], color="green", label="Indoor TVOC")
plt.plot(excel["Time"], excel["Outdoor TVOC"], color="red", label="Outdoor TVOC")
plt.xlabel("Time(s)")
plt.ylabel("TVOC(mg/m³)")
plt.legend(loc="best")
plt.savefig("TVOC.png")
plt.close()

plt.plot(excel["Time"], excel["Indoor CO2"], color="green", label="Indoor CO2")
plt.plot(excel["Time"], excel["Outdoor CO2"], color="red", label="Outdoor CO2")
plt.xlabel("Time(s)")
plt.ylabel("CO2(ppm)")
plt.legend(loc="best")
plt.savefig("CO2.png")
plt.close()